### ISSUE TITLE
Fix TypeError: Cannot read property 'Y' of undefined

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-provider-anvil#10]
```
     TypeError: Cannot read property 'Y' of undefined
      at readSection (dist/chunk.js:60:15)
      at dist/chunk.js:42:12
      at Array.forEach (native)
      at readSections (dist/chunk.js:41:12)
      at nbtChunkToPrismarineChunk (dist/chunk.js:19:3)
      at Context.<anonymous> (distTest/chunkToNbt.js:47:19)
```

somehow updating some dependencies produce that.

Basically loading fails. Is it because saving failed or ?

**Comment by rom1504** [comment]
related to https://github.com/PrismarineJS/prismarine-world/pull/13
