### ISSUE TITLE
TypeError: palette is not iterable

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/prismarine-provider-anvil#27]
I've been having this error a lot
at `prismarine-provider-anvil/src/1.14/chunk.js:129:26`
I added a console.log and sometimes `readPalette` is called with undefined `palette` parameter

stack: 
```
    at readPalette (project/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:129:26)
    at readSection (project/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:78:9)
    at project/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:50:35
    at Array.forEach (<anonymous>)
    at readSections (project/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:50:16)
    at nbtChunkToPrismarineChunk (project/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:12:7)
    at Anvil.load (project/node_modules/prismarine-provider-anvil/src/anvil.js:34:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by ghost** [comment]
The error goes away if I replace 
`function readBlocks (section, blockStates) {` with `function readBlocks (section, blockStates=[]) {`
and `function readPalette (section, palette) {` with `function readPalette (section, palette=[]) {`

I get a valid (looking) chunk but I don't think the actual issue is fixed
